import re
class pattern():
	#format: (reg_expression: pattern_name)
	patterns=[
	(r"\n*((.+?)\d+:\d+:) error: conflicting types for [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*",  "conflicting types for a function"),
	(r"\n*((.+?)\d+:\d+:) error: read-only variable is not assignable", "read-only variable is not assignable"),
	(r"\n*((.+?)\d+:\d+:) error: expected expression","expected expression"),
	(r"\n*((.+?)\d+:\d+:) error: [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* where arithmetic or pointer type is required", 'typecasting pointer'),
	(r"\n*((.+?)\d+:\d+:) error: no member named \'\_[0-9]*\_[0-9]*\_\' in", 'no member named _offset_size_'),
	(r"\n*((.+?)\d+:\d+:) error: no member named \'field\_[a-zA-Z0-9]*\' in", 'no member named field_0x?'),
	(r"\n*((.+?)\d+:\d+:) error: no member named [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* in", 'no member named ?'),
	(r"\n*((.+?)\d+:\d+:) error: invalid operands to binary expression [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "invalid operands to binary expression"),
	(r"\n*((.+?)\d+:\d+:) error: member reference type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is a pointer; did you mean to use '->'\?", "member reference type is a pointer"),
	(r"\n*((.+?)\d+:\d+:) error: member reference type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is not a pointer", "member reference type is not a pointer"),
	(r"\n*((.+?)\d+:\d+:) error: member reference base type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is not a structure or union","member reference type is not a structure or union"),
	(r"\n*((.+?)\d+:\d+:) error: must use '(struct|union|enum)' tag to refer to type", "must use '(struct|union|enum)' tag to refer to type"),
	(r"\n*((.+?)\d+:\d+:) error: use of undeclared identifier", "use of undeclared identifier"),
	(r"\n*((.+?)\d+:\d+:) error: operand of type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* cannot be cast to a pointer type","operand of type 'one type' cannot be cast to a pointer type"),
	(r"\n*((.+?)\d+:\d+:) error: (unknown|unexpected) type name", "unknown type name"),
	(r"(In function `{}':\n*((.+?):\d+:\d*:*) undefined reference to `(.*)'|\n*(.+?):\d+:\d+: warning: implicit declaration of function '(.+?)' is invalid in C99 \[-Wimplicit-function-declaration\].*?\n(.+?)\n)", "undefined reference to a function"),
	(r"\n*((.+?)\d+:\d+:) error: expected \'[\;\)\]\(\[\{\}]*\'", "expected 'some symbol'"),
	(r"\n*((.+?)\d+:\d+:) error: [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is not assignable", "type 'A' is not assignable"),
	(r"\n*((.+?)\d+:\d+:) error: \#endif without \#if", "#endif without #if"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of label [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "redefinition of label"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of parameter [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "redefinition of parameter"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* as different kind of symbol", "redefinition of 'A' as different kind of symbol"),
	(r"\n*((.+?)\d+:\d+:) error: [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* cannot be cast to type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "cannot be cast to type"),
	(r"\n*((.+?)\d+:\d+:) error: too (many|few) arguments to function call[a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","too many|few arguments to function call"),
	(r"\n*((.+?)\d+:\d+:) error: function cannot return [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* type", "function cannot return some type"),
	(r"\n*((.+?)\d+:\d+:) error: assigning to [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* from incompatible type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "assigning to type A from incompatible type B"),
	(r"\n*((.+?)\d+:\d+:) error: subscripted value is not an array\, pointer\, or vector","subscripted value is not an array, pointer, or vector"),
	(r"\n*((.+?)\d+:\d+:) error: parameter name omitted", "parameter name omitted"),
	(r"\n*((.+?)\d+:\d+:) error: passing [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* to parameter of incompatible type", "passing sth to parameter of incompatible type"),
	(r"\n*((.+?)\d+:\d+:) error: invalid argument type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "invalid argument type"),
	(r"\n*((.+?)\d+:\d+:) error: incomplete definition of type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "incomplete definition of type"),
	(r"\n*((.+?)\d+:\d+:) error: reference to overloaded function could not be resolved", "reference to overloaded function could not be resolved"),
	(r"\n*((.+?)\d+:\d+:) error: called object type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is not a function or function pointer" ,"called object type 'int' is not a function or function pointer"),
	(r"\n*((.+?)\d+:\d+:) error: duplicate case value",'duplicate case value'),
	(r"\n*((.+?)\d+:\d+:) error: address of overloaded function [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* does not match required type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "address of overloaded function 'A' does not match required type 'B'"),
	(r"\n*((.+?)\d+:\d+:) error: attempt to use a poisoned identifier", "attempt to use a poisoned identifier"),
	(r"\n*((.+?)\d+:\d+:) error: indirection requires pointer operand", "indirection requires pointer operand"),
	(r"\n*((.+?)\d+:\d+:) error: operand of type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is required", "operand of type ? is required"),
	(r"\n*((.+?)\d+:\d+:) error: parameter name omitted", "parameter name omitted"),
	(r"\n*((.+?)\d+:\d+:) error: pointer cannot be cast to type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "pointer cannot be cast to type ?"),
	(r"\n*((.+?)\d+:\d+:) error: too few arguments provided to function-like macro invocation", "too few arguments provided to function-like macro invocation"),
	(r"\n*((.+?)\d+:\d+:) error: returning [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* from a function with incompatible result type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "returning type A from a function with incompatible result type B"),
	(r"\n*((.+?)\d+:\d+:) error: use of undeclared label [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "use of undeclared label"),
	(r"\n*((.+?)\d+:\d+:) error: expected statement", "expected statement"),
	(r"\n*((.+?)\d+:\d+:) error: subscript of pointer to function type", "subscript of pointer to function type"),
	(r"\n*((.+?)\d+:\d+:) error: expected identifier or '\('", "expected identifier or '('"),
	(r"\n*((.+?)\d+:\d+:) error: cannot combine with previous [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* declaration specifier",'cannot combine with previous declaration specifier'),
	(r"\n*((.+?)\d+:\d+:) error: subscript of pointer to incomplete type","subscript of pointer to incomplete type"),
	(r"\n*((.+?)\d+:\d+:) error: statement requires expression of scalar type", "statement requires expression of scalar type"),
	(r"\n*((.+?)\d+:\d+:) error: static declaration of [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* follows non-static declaration", "static declaration of 'A' follows non-static declaration"),
	#### + IDA Patterns
	(r"\n*((.+?):\d+:\d+:) error: use of undeclared identifier '(_OWORD)'\n(\s*?.+?)\n", "use of undeclared identifier"),
	# (r"\n*((.+?):\d+:\d+:) error: use of undeclared identifier '(_OWORD)'\n(\s*?.+?)\n","undeclared identifier OWORD"),
	(r"\n*(.+?):\d+:\d+: error: unknown type name (?:\xe2\x80\x98|')(.*?va_list.*?)(?:\xe2\x80\x99|').*?\n(\s*?.+?)\n","unknown type name va_list"),
	(r"\n*((.+?):\d+:\d+:) error: (\xe2\x80\x98((.+)_\d*)\xe2\x80\x99 undeclared \(first use in this function\)|use of undeclared identifier '((.+?)_\d+)')(?:; did you mean (?:.+?)|)\n  rror: use of undeclared identifier '((?:off|dword|qword|asc|unk)_[0-9,A-F]+|(.+))'.*?\n(\s*?.+?)\n","undeclared identifiers datatypes"),
	(r"\n*((.+?)\d+:\d+:) error: expected \'","expected apostrophe near declaration specifiers"),
	(r"\n*((.+?)\d+:\d+:) error: extraneous \'\)' before","extraneous bracket"),
	(r"\n*((.+?)\d+:\d+:) error: variable has incomplete type","variable has incomplete type"),
	(r"\n*((.+?)\d+:\d+:) error: incompatible integer to pointer conversion assigning","incompatible integer to pointer conversion assigning"),
	(r"\n*((.+?)\d+:\d+:) error: expected function body after function declarator","expected function body after function declarator"),
	(r"\n*((.+?)\d+:\d+:) error: too many arguments to function call","too many arguments to function call"),
	(r"\n*((.+?)\d+:\d+:) error: ISO C requires a named parameter before","ISO C requires a named parameter before"),
	(r"\n*((.+?)\d+:\d+:) error: function cannot return function type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","function cannot return function type"),
	(r"\n*((.+?)\d+:\d+:) error: unexpected type name [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* expected expression","unexpected type name"),
	(r"\n*((.+?)\d+:\d+:) error: too many arguments provided to function-like macro invocation","too many arguments provided to function-like macro invocation"),
	(r"\n*((.+?)\d+:\d+:) error: a parameter list without types is only allowed in a function definition","a parameter list without types is only allowed in a function definition"),
	(r"\n*((.+?)\d+:\d+:) error: non-object type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* is not assignable","non-object type"),
	(r"\n*((.+?)\d+:\d+:) error: cannot decrement value of type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","cannot decrement value of type"),
	(r"\n*((.+?)\d+:\d+:) error: array subscript is not an integer","array subscript is not an integer"),
	(r"\n*((.+?)\d+:\d+:) error: statement requires expression of integer type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*", "statement requires expression of integer type"),
	(r"\n*((.+?)\d+:\d+:) error: incompatible pointer to integer conversion assigning to","incompatible pointer to integer conversion assigning to"),
	(r"\n*((.+?)\d+:\d+:) error: offset of incomplete type","offset of incomplete type"),
	(r"\n*((.+?)\d+:\d+:) error: incompatible integer to pointer conversion assigning to","incompatible integer to pointer conversion assigning to"),
	(r"\n*((.+?)\d+:\d+:) error: invalid application of [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* to an incomplete type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","invalid application of"),
	(r"\n*((.+?)\d+:\d+:) error: non-void function [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* should return a val","non-void function should return a val"),
	(r"\n*((.+?)\d+:\d+:) error: non-void function [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* declared as a function","declared as a function"),
	(r"\n*((.+?)\d+:\d+:) error: invalid conversion between vector type \'\_\_m128d\' (vector of 2 \'double\' values) and integer type 'unsigned long long' of different size","invalid conversion between vector type __m128d"),
	(r"tentative definition has type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* that is never completed","tentative definition has type"),
	(r"\n*((.+?)\d+:\d+:) error: cannot assign to variable [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* with const-qualified type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","cannot assign to variable"),
	(r"\n*((.+?)\d+:\d+:) error: [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* and [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* (aka [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*) are not pointers to compatible types","not pointers to compatible types"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'\_\_int64\'","redefinition of __int64"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'\_\_int32\'","redefinition of __int32"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'\_\_int16\'","redefinition of __int16"),	
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'\_\_int8\'","redefinition of __int8"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'\_\_ptr32\'","redefinition of __ptr32"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'yylex\'","redefinition of yylex"),
	(r"\n*((.+?)\d+:\d+:) error: expression is not assignable","expression is not assignable"),
	(r"\n*((.+?)\d+:\d+:) error: extraneous closing brace \(","extraneous closing brace ("),
	(r"\n*((.+?)\d+:\d+:) error: expected identifier","expected identifier"),
	(r"\n*((.+?)\d+:\d+:) error: called object type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\<\:\/]* is not a function or function pointer" ,"called object type '<dependent type>' is not a function or function pointer"),
	(r"\n*((.+?)\d+:\d+:) error: redefinition of \'free\_INSN\_LIST\_list\'","redefinition of free_inst_list"),
	(r"\n*((.+?)\d+:\d+:) error: [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* and [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* are not pointers to compatible types","not pointers to compatible types"),
	(r"\n*((.+?)\d+:\d+:) error: cannot take the address of an rvalue of type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*","cannot take an address of an rvalue of type struct"),
	(r"\n*((.+?)\d+:\d+:) error: cannot assign to non-static data member [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* with const-qualified type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* (aka [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]*)","cannot assign to non-static data member with const-qualified type"),
	(r"\n*((.+?)\d+:\d+:) error: \'inline\' can only appear on functions","inline can only appear on functions"),
	(r"\n*((.+?)\d+:\d+:) error: invalid suffix [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/]* on integer constant","invalid suffix on integer constant"),
	(r"\n*((.+?)\d+:\d+:) error: invalid [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]* at end of declaration\; did you mean [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]*\?","invalid A at end of declaration; did you mean B?"),
	(r"\n*((.+?)\d+:\d+:) error: invalid conversion between vector type \'\_\_m128i\' (vector of 2 \'long long\' values) and integer type \'uint32\' of different size","invalid conversion between vector type __m128d and uint32"),
	(r"\n*((.+?)\d+:\d+:) error: invalid conversion between vector type \'__m128i\' (vector of 2 \'long long\' values) and integer type \'uint32\' (aka \'unsigned int\') of different size","invalid conversion between __m128d and uint32"),
	(r"\n*((.+?)\d+:\d+:) error: invalid conversion between vector type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]* (vector of 2 [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]* values) and integer type [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]* (aka [a-zA-Z0-9\s\_\[\]\*\(\)\'\,\"\;\&\.\-\>\:\/\+\=]*) of different size","invalid conversion between vector types and standard types")
]